In [35]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 30)
pd.set_option('display.precision', 3)
pd_version = pd.__version__
np_version = np.__version__
cols = [
    '', 'region', 'area', 'palmitic', 'palmitoleic', 'stearic', 'oleic', 'linoleic', 'linolenic', 'arachidic', 'eicosenoic'
]
df = pd.read_csv('http://s3.amazonaws.com/istreet-assets/cqj0wXOp6sICdTRWc5X2cw/olive.csv.txt')


In [36]:
df.shape

(572, 11)

In [37]:
df_data_types_count = df.dtypes.value_counts()


In [38]:
print(df_data_types_count)

int64     10
object     1
dtype: int64


In [39]:
df['sub_region_raw'] = df['Unnamed: 0']   


In [40]:
df.head()

Unnamed: 0  region  area  palmitic  palmitoleic  stearic  oleic  \
0  1.North-Apulia       1     1      1075           75      226   7823   
1  2.North-Apulia       1     1      1088           73      224   7709   
2  3.North-Apulia       1     1       911           54      246   8113   
3  4.North-Apulia       1     1       966           57      240   7952   
4  5.North-Apulia       1     1      1051           67      259   7771   

   linoleic  linolenic  arachidic  eicosenoic  sub_region_raw  
0       672         36         60          29  1.North-Apulia  
1       781         31         61          29  2.North-Apulia  
2       549         31         63          29  3.North-Apulia  
3       619         50         78          35  4.North-Apulia  
4       672         50         80          46  5.North-Apulia

In [41]:
# Q8: In `df`, create a new column 'sub_region_raw', which will be a copy of the column 'Unnamed: 0'
df['sub_region_raw'] = df['Unnamed: 0']   
# Q9: In `df`, rename 'Unnamed: 0' to 'sub_region_desc'
df.rename(columns={'Unnamed: 0': 'sub_region_desc'}, inplace=True)
# Q10: In `df`, rename the column 'area' to: 'sub_region'
df.rename(columns={'area': 'sub_region'}, inplace=True)


In [42]:
type(df_data_types_count)

pandas.core.series.Series

In [43]:
u_sub_region = df.sub_region.unique()

In [44]:
u_sub_region.size

9

In [45]:
df.region.unique()


array([1, 2, 3], dtype=int64)

In [34]:
pd.DataFrame(df.sub_region_desc.str.split('.',1).tolist(), columns = ['numindex','sub_region_desc'])

numindex sub_region_desc
0          1    North-Apulia
1          2    North-Apulia
2          3    North-Apulia
3          4    North-Apulia
4          5    North-Apulia
..       ...             ...
567      568    West-Liguria
568      569    West-Liguria
569      570    West-Liguria
570      571    West-Liguria
571      572    West-Liguria

[572 rows x 2 columns]

In [52]:
df.sub_region_desc.str.lstrip('1234567890.').unique()


array(['North-Apulia', 'Calabria', 'South-Apulia', 'Sicily',
       'Inland-Sardinia', 'Coast-Sardinia', 'Umbria', 'East-Liguria',
       'West-Liguria'], dtype=object)

In [51]:
df.sub_region_desc

0        1.North-Apulia
1        2.North-Apulia
2        3.North-Apulia
3        4.North-Apulia
4        5.North-Apulia
             ...       
567    568.West-Liguria
568    569.West-Liguria
569    570.West-Liguria
570    571.West-Liguria
571    572.West-Liguria
Name: sub_region_desc, Length: 572, dtype: object

In [ ]:
# WARNING: If you close your browser, your work will be LOST!

# Q1: import numpy and pandas
import numpy as np
import pandas as pd
# Q2: Set options in pandas so it displays 30 `max_rows` 
#                                 no limit on `max_columns`
#                                 precision is 3
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 30)
pd.set_option('display.precision', 3)
# Q3: assign the versions of pandas and numpy to variables below
pd_version = pd.__version__
np_version = np.__version__

# Q4: Read in the csv file "olive.csv" with pandas. 
#     The filename is stored in the variable `olive_path`
#     Assign it to variable `df`

df = pd.read_csv('olive.csv')



# The fields are:

# Unnamed: 0
# region
# area
# palmitic
# palmitoleic
# stearic
# oleic
# linoleic
# linolenic
# arachidic
# eicosenoic



# Q5: How many rows and columns are there in `df`? Put your answer in a variable `df_shape`.
df_shape = df.shape

# Q6: assign the first 2 rows of `df` to `df_first_two`
df_first_two = df.head(2)

# Q7: How many distinct data types are there in `df`?
dtcount = df.dtypes.value_counts()

df_data_types_count =  dtcount[0]
 # this should be an integer

# Q8: In `df`, create a new column 'sub_region_raw', which will be a copy of the column 'Unnamed: 0'
df['sub_region_raw'] = df['Unnamed: 0']   
# Q9: In `df`, rename 'Unnamed: 0' to 'sub_region_desc'
df.rename(columns={'Unnamed: 0': 'sub_region_desc'}, inplace=True)
# Q10: In `df`, rename the column 'area' to: 'sub_region'
df.rename(columns={'area': 'sub_region'}, inplace=True)
# Q11: In `df`, get the unique values of the field 'region'
region_unique = df.region.unique()

# Q12: In `df`, how many unique values of the field 'sub_region' are there?
u_sub_region = df.sub_region.unique() 

sub_region_unique_count = u_sub_region.size  # should be an integer

# Q13: Lets take a look at the field `sub_region_desc`:

# >>> df['sub_region_desc'].head(5)
# 0    1.North-Apulia
# 1    2.North-Apulia
# 2    3.North-Apulia
# 3    4.North-Apulia
# 4    5.North-Apulia

# Looks like 'sub_region_desc' has line numbers attached to the beginning of region name. Remove those and get the unique values in that field, assign it to `srd_unique`
srd_unique = df.sub_region_desc.str.lstrip('1234567890.').unique()




In [ ]:

#
# # Q1: import numpy and pandas
# import pandas as pd
# import numpy as np
#
# # Q2: Set options in pandas so it displays 10 `max_rows`
# #                                 no limit on `max_columns`
# #                                 precision is 3
# pd.options.display.max_rows = 30
# pd.options.display.max_columns = None
# pd.options.display.precision = 3
#
#
# # Q3: assign the versions of pandas and numpy to variables below
# pd_version = pd.__version__
# np_version = np.__version__
#
# # Q4: Read in the csv file "olive.csv" with pandas.
# #     Assign it to variable `df`
# df = pd.read_csv('olive.csv')
#
# # The fields are:
#
# # Unnamed: 0
# # region
# # area
# # palmitic
# # palmitoleic
# # stearic
# # oleic
# # linoleic
# # linolenic
# # arachidic
# # eicosenoic
#
#
# # Q5: How many rows and columns are there in `df`? Put your answer in a variable `df_shape`.
# df_shape = df.shape
#
# # Q6: assign the first 2 rows of `df` to `df_first_2`
# df_first_two = df.head(2)
#
# # Q7: How many distinct data types are there in `df`?
# df_data_types_count = len(df.dtypes.unique())   # this should be an integer
#
# # Q8: In `df`, create a new column 'sub_region_raw', which will be a copy of the column 'Unnamed: 0'
# df['sub_region_raw'] = df['Unnamed: 0']
#
# # Q9: In `df`, rename 'Unnamed: 0' to 'sub_region_desc'
# df.rename(columns={'Unnamed: 0': 'sub_region_desc'}, inplace=1)
#
# # Q10: In `df`, rename the column 'area' to: 'sub_region'
# df.rename(columns={'area': 'sub_region'}, inplace=1)
#
# # Q11: In `df`, get the unique values of the field 'region'
# region_unique = df['region'].unique()
#
# # Q12: In `df`, how many unique values of the field 'sub_region' are there?
# sub_region_unique_count = len(df['sub_region'].unique())  # should be an integer
#
# # Q13: Lets take a look at the field `sub_region_desc`:
#
# # >>> df['sub_region_desc'].head(5)
# # 0    1.North-Apulia
# # 1    2.North-Apulia
# # 2    3.North-Apulia
# # 3    4.North-Apulia
# # 4    5.North-Apulia
#
# # Looks like 'sub_region_desc' has line numbers attached to the beginning of region name. Remove those and get the unique values in that field, assign it to `srd_unique`
# srd_unique = df['sub_region_desc'].map(lambda r: r.split('.')[-1]).unique()

In [54]:
region_unique = df.sub_region.unique()



In [59]:
print(u_sub_region.size)

9


In [60]:
len(df['sub_region'].unique()) 

9

In [62]:
import numpy as np


# Do not change these variables
A = np.array([[1,2,3],[2,7,4]])
B = np.array([[1,-1],[0,1]])
C = np.array([[5,-1],[9,1],[6,0]])
D = np.array([[3,-2,-1],[1,2,3]])

u = np.array([6,2,-3,5])
v = np.array([3,5,-1,4])

# Q1: record the dimensions of A, B, C, D, u, v respectively in the dict below. 
#     Do not type the answers, make python do the work

dimensions = {
    'A': A.shape,
    'B': B.shape,
    'C': C.shape,
    'D': D.shape,
    'u': u.shape,
    'v': v.shape
}

# Q2: vector operations
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work
alpha = 6

u_plus_v = np.add(u,v)           # u+v
u_minus_v =  np.subtract(u,v)          # u-v
alpha_times_u = np.multiply(alpha,u)       # alpha * u, alpha = 6
u_dot_v = np.dot(u,v)             # u . v
norm_u =   np.linalg.norm(u)            # ||u|| 


# Q3: compute the following and assign to variables below:
#     assign `None` if the operation is not defined
#     do not type the answers, make python do the work

A_plus_C = None             # A + C
A_minus_Ctranspose = np.subtract(A,C.T)   # A - C.T
Ctranspose_plus_3D = np.add(C.T, 3*D)    # C.T + 3*D
B_times_A =   np.dot(B, A)          # B*A
B_times_Atranspose = None   # B*A.T

In [63]:
B_times_A


array([[-1, -5, -1],
       [ 2,  7,  4]])

In [64]:
np.dot(np.dot(B,B),np.dot(B,B))


array([[ 1, -4],
       [ 0,  1]])